### ISSUE TITLE
Wrong zoom to JOSM

### ISSUE THREAD

**Issue by 02JanDal** [02JanDal/osm-bjk#21]
https://community.openstreetmap.org/t/verktyg-for-att-berakna-visa-och-atgarda-saker-i-osm-utifran-oppna-data/107713/37

> Load and zoom-koordinaterna är fel (tror jag). T.ex. [BästaJävlaKartan](https://osm-bjk.jandal.se/deviations/81555) zoomar kartan till [ 10.506934103893087, -0.003968775912321777, 10.515893109178652, 0.005050657559749542 ] vilket blir helt fel (någonstans i Gabon, [OpenStreetMap](https://www.openstreetmap.org/#map=10/0.0000/10.0000)). Det verkar som koden byter koordinatsystem innan den skickar över det till JOSM.

**Comment by Prillan** [comment]
Detta verkar fixat nu? Hursomhelst, det jag såg igår var att `geom.getExtent()` inte gav koordinater i SWEREF 99, så antar att det är fixat på något sätt? 
[https://github.com/02jandal/osm-bjk/blob/main/frontend/src/pages/deviation.tsx#L57`](https://github.com/02JanDal/osm-bjk/blob/ba1eea14ac96f951cfada141f516f1da8660362f/frontend/src/pages/deviation.tsx#L57)

**Comment by 02JanDal** [comment]
Har inte gjort något, men kan inte heller återskapa det nu. Stänger för stunden så hoppas vi att det inte dyker upp igen!
